ZadanieApis/ZadanieApis/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using ZadanieApis;
using ZadanieApis.Models;

public class AdminController : Controller
{
    private MyDbContext db = new MyDbContext();

    public ActionResult Admin()
    {
        List<Orders> orders = db.Orders.ToList();
        return View(orders ?? new List<Orders>());
    }

    [HttpPost]
    public ActionResult UpdateStatus(int orderId, string newStatus)
    {
        var order = db.Orders.Find(orderId);

        if (order != null)
        {
            order.Status = newStatus;

            if (newStatus == "Received")
            {
                db.Orders.Remove(order);
            }

            db.SaveChanges();
        }

        return Json(new { success = true });
    }
    public ActionResult GetLatestOrders()
    {
        List<Orders> latestOrders = db.Orders.ToList();
        return Json(latestOrders);

    }
}

ZadanieApis/ZadanieApis/Views/Admin/Admin.cshtml
@model List<Orders>

<h2>Admin Page - Orders</h2>

<table class="table">
    <thead>
        <tr>
            <th>Order ID</th>
            <th>User ID</th>
            <th>Order Date</th>
            <th>Product UIDs</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model)
        {
            <tr>
                <td>@order.OrderID</td>
                <td>@order.UserID</td>
                <td>@order.OrderDate</td>
                <td>@order.ProductUIDs</td>
                <td>
                    <span id="status_@order.OrderID">@order.Status</span>
                    <select id="statusSelect_@order.OrderID">
                        <option value="Pending" selected="@(order.Status == "Pending")">Pending</option>
                        <option value="Processing" selected="@(order.Status == "Processing")">Processing</option>
                        <option value="Shipping" selected="@(order.Status == "Shipping")">Shipping</option>
                        <option value="Received" selected="@(order.Status == "Received")">Received</option>
                    </select>
                </td>
                <td>
                    <button class="btn btn-primary" onclick="updateStatus(@order.OrderID)">Update Status</button>
                </td>
            </tr>
        }
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
    function updateStatus(orderId) {
        var newStatus = $("#statusSelect_" + orderId).val();

        $.ajax({
            type: 'POST',
            url: '@Url.Action("UpdateStatus", "Admin")',
            data: { orderId: orderId, newStatus: newStatus },
            success: function (data) {
                if (data.success) {
                    // Update the displayed status
                    $("#status_" + orderId).text(newStatus);
                    // Poll the server for the latest orders after an update
                    pollForLatestOrders();
                }
            },
            error: function (error) {
                console.log(error);
            }
        });
    }

    function pollForLatestOrders() {
        // Poll the server for the latest orders every 5 seconds
        setInterval(function () {
            $.ajax({
                type: 'GET',
                url: '@Url.Action("GetLatestOrders", "Admin")',
                success: function (latestOrders) {
                    // Update the page with the latest orders
                    updatePageWithLatestOrders(latestOrders);
                },
                error: function (error) {
                    console.log(error);
                }
            });
        }, 5000); 
    }

    function updatePageWithLatestOrders(latestOrders) {

        location.reload();
    }

    pollForLatestOrders();
</script>